### ISSUE TITLE
China_A_share_market_tushare.py  run incorrect

### ISSUE THREAD

**Issue by xzl339** [AI4Finance-Foundation/FinRL-Tutorials#91]
I meet some question when I  run China_A_share_market_tushare.py :
Traceback (most recent call last):

  File "D:\anaconda3\envs\FinRL\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "d:\mypython\ai4finance foundation\finrl-meta-master\china_a_share_market_baostock0.py", line 384, in <module>
    trading()

  File "d:\mypython\ai4finance foundation\finrl-meta-master\china_a_share_market_baostock0.py", line 317, in trading
    plotter.plot()

  File "D:\mypython\AI4Finance Foundation\FinRL-Meta-master\meta\data_processors\baostock.py", line 184, in plot
    plt.plot(time, baseline, label=baseline_label, color="grey")

  File "D:\anaconda3\envs\FinRL\lib\site-packages\matplotlib\pyplot.py", line 2769, in plot
    **({"data": data} if data is not None else {}), **kwargs)

  File "D:\anaconda3\envs\FinRL\lib\site-packages\matplotlib\axes\_axes.py", line 1635, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]

  File "D:\anaconda3\envs\FinRL\lib\site-packages\matplotlib\axes\_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)

  File "D:\anaconda3\envs\FinRL\lib\site-packages\matplotlib\axes\_base.py", line 498, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "

ValueError: x and y must have same first dimension, but have shapes (128,) and (129,)

**Comment by leozhang9** [comment]
We ran into the same problem. Before this error occurred, I manually changed the date column name to time, and there was a '//' unsupported error. Finally, I ran into this problem:
ValueError: x and y must have same first dimension, but have shapes (103,) and (104,)
